### ISSUE TITLE
Invalid flagging of faulty `...` usage (part 2)

### ISSUE THREAD

**Issue by DavisVaughan** [HenrikBengtsson/globals#72]
Follow up of #62, after receiving this comment https://github.com/HenrikBengtsson/globals/issues/62#issuecomment-758276101 reproduced below:

``` r
library(purrr)
library(future)

catcher <- function(x) {
  map(x, ~list(...))
}

catcher(list(1:2, 1:3))
#> [[1]]
#> [[1]][[1]]
#> [1] 1 2
#> 
#> 
#> [[2]]
#> [[2]][[1]]
#> [1] 1 2 3

future({
  catcher(list(1:2, 1:3))
})
#> Error in getGlobalsAndPackages(expr, envir = envir, tweak = tweakExpression, : Did you mean to create the future within a function?  Invalid future expression tries to use global '...' variables that do not exist: {; catcher(list(1:2, 1:3)); }
```

<sup>Created on 2021-01-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

It looks like the dots are being returned as an `NA` that gets wrapped with the `DotDotDotList` class.
https://github.com/HenrikBengtsson/globals/commit/a05c813bd95c86695dde4feba2f1fba459276367#diff-7b1d4e2796df08171808d5d5341fadf8c78a22cc2ee1c2874cc4d3ebb2504dcbR233

But then in `future::getGlobalsAndPackages()`, it checks to make sure that the dots are a list, and errors otherwise (as we see above) https://github.com/HenrikBengtsson/future/blob/0755d6f30219f596f27f948a1e1df1a6ddc71ed0/R/globals.R#L174

Maybe instead of `NA`, it should be setting `ddd` to `list()` in some cases like this one? That is my initial guess.

**Comment by HenrikBengtsson** [comment]
Thxs. Finally got around to this one.  I decided to fix this for now in **future**, cf. https://github.com/HenrikBengtsson/future/commit/89d28d83f4f689c543d6a88aaa41137af512598f.  

I think the original reason to return an `structure(NA, class = "DotDotDotList")` was to be conservative and catch cases like this that I couldn't foresee at the time.  I think the proper, long-term fix is to not return a `globals[["..."]]` element at all, because it's not a global.  I'll create a separate issue for that.
